### ISSUE TITLE
20. 결제 패턴 분석 웹서비스 개발

### ISSUE THREAD

**Issue by Kang-heesuk** [NAVER-CAMPUS-HACKDAY/common#15]
## 주제 : 결제 패턴 분석 웹서비스 개발
!본 주제의 우수참가자로 선정시 'NAVER'에서 '채용전환형 인턴십'의 참여기회가 주어집니다.

### 주제선정 배경
* 대용량 결제 데이터를 분석하여 의미 있는 결과 도출 및 시각화

### 개발 요구사항 (필수)
* 데이터셋을 받을 수 있는 인터페이스 개발 ( e.g. File stream 등 )
* 주어진 데이터셋을 기반으로 유의미한 데이터 도출
* 데이터 분석 알고리즘 설계 및 개발
* 결제 데이터 패턴 분석 결과 제공 웹서비스 개발

### 개발 요구사항 (선택)
* 설계 시스템의 class & sequence diagram

### 개발언어 
* Java, Javascript & HTML

### 플랫폼
* 웹

### 기타사항
* 분석을 위해 사용 할 가상의 사용자별 결제 데이터는 CSV 포맷으로 제공 ( 약 1만 row )

**Comment by seongahjo** [comment]
안녕하세요. 질문이 있습니다.
태그는 체험형 인턴십인데 본문에는 채용형 인턴십으로 되있네요.
어느게 맞는지 궁금합니다.

**Comment by Kang-heesuk** [comment]
@seongahjo 채용전환형이 맞습니다. 혼란드려서 죄송합니다.
