### ISSUE TITLE
16. 안드로이드/아이폰 광고 Mediation 라이브러리

### ISSUE THREAD

**Issue by Kang-heesuk** [NAVER-CAMPUS-HACKDAY/common#16]
## 주제 : 16. 안드로이드/아이폰 광고 Mediation 라이브러리
우수참가자로 선정시 'NAVER'에서 '채용전환형 인턴십'의 참여기회가 주어집니다. (20년 2월 이내 졸업예정자 우대)

### 주제선정 배경
* 앱 환경의 수익 최대화를 위한 다양한 광고플랫폼들의 광고를 선별하여 제공해 줄 수 있는 라이브러리가 필요함.
예) 구글 admob 광고 건 당 단가 1원에 전체 인벤토리에 50% 정도에 광고 제공 가능, 페이스북 광고 건당 5원에 10% 제공 가능한 상황등을 고려하여 수익을 최대화하기 위한 Mediation 라이브러리 개발

### 개발 요구 사항 (필수)
- 2가지 이상의 광고 SDK 를 활용한 광고 Mediation SDK 를 개발.
- 광고 정보 송출 서버는 Mock 으로 대체.
- 예시
  1. 배너광고 렌더링을 위해서 광고 서버에 배너광고에 대한 데이터를 요청.
  2. 구글, 페이스북, 인모비 순으로 광고 data 를 받음.
  3. 서버 응답값을 토대로 렌더링이 성공할 때까지 순회하면서 배너광고를 렌더링.
      - 구글 광고 rendering 에 성공했다면 페이스북, 인모비의 광고는 렌더링 하지 않아도 됨.
      - 구글 광고 rendering 에 실패했다면 페이스북 광고를 렌더링 시도함.
      - 마지막 인모비 광고 data 로 광고 렌더링 실패할 경우는 광고를 렌더링 하지 않음.
- 완성된 광고 SDK 를 테스트 할 수 있는 예제 App 개발.
- Android/iOS 환경 중에서 택 1.
- 배너형 광고 (Web Banner) 로 노출.

### 개발 요구 사항 (선택)
- 광고를 load 한 이후에 5000ms 안에는 렌더링이 완료될 것.
  - 5000ms 이 지나면 timeout 에러.
- 리스트에 배너 광고를 렌더링. 
  - 특정 간격마다 광고를 추가.
  - 리스트를 스크롤 할 경우에 기존 광고가 유지되어야 함. 예를 들어서 10 번째 줄에 배너광고가 추가되어 있고 스크롤 이후 다시 10번째 줄로 돌아올 경우, 기존 광고가 렌더링 되어야 함.

### Role
* Mobile Developer
* AdTech Developer

### Technology 
* Android
* iOS
* Git

### 개발언어
* Java
* Kotlin
* Swift
* Objective-C

### 기타사항
* 2개 이상의 광고 SDK를 활용해야함
* 각종 오픈소스 라이브러리 사용 가능
* 서버 기능 필요 시 Mock으로 대체 가능
* 노트북은 맥북 혹은 윈도우, 에뮬레이터가 잘 구동되는 수준 및 앱 개발에 필요한 소프트웨어 필요

**Comment by kidoo312** [comment]
변경사항 수정 부탁드립니다:)

개발 요구 사항 (필수)
- 2가지 이상의 광고 SDK 를 활용한 광고 Mediation SDK 를 개발.
- 광고 정보 송출 서버는 Mock 으로 대체.
- 예시
  1. 배너광고 렌더링을 위해서 광고 서버에 배너광고에 대한 데이터를 요청.
  2. 구글, 페이스북, 인모비 순으로 광고 data 를 받음.
  3. 서버 응답값을 토대로 렌더링이 성공할 때까지 순회하면서 배너광고를 렌더링.
      - 구글 광고 rendering 에 성공했다면 페이스북, 인모비의 광고는 렌더링 하지 않아도 됨.
      - 구글 광고 rendering 에 실패했다면 페이스북 광고를 렌더링 시도함.
      - 마지막 인모비 광고 data 로 광고 렌더링 실패할 경우는 광고를 렌더링 하지 않음.
- 완성된 광고 SDK 를 테스트 할 수 있는 예제 App 개발.
- Android/iOS 환경 중에서 택 1.
- 배너형 광고 (Web Banner) 로 노출.

개발 요구 사항 (선택)
- 광고를 load 한 이후에 5000ms 안에는 렌더링이 완료될 것.
  - 5000ms 이 지나면 timeout 에러.
- 리스트에 배너 광고를 렌더링. 
  - 특정 간격마다 광고를 추가.
  - 리스트를 스크롤 할 경우에 기존 광고가 유지되어야 함. 예를 들어서 10 번째 줄에 배너광고가 추가되어 있고 스크롤 이후 다시 10번째 줄로 돌아올 경우, 기존 광고가 렌더링 되어야 함.
