### ISSUE TITLE
21. 전기자동차 이용 시 진행 가능한 최소시간 경로 탐색 기능 구현

### ISSUE THREAD

**Issue by Kang-heesuk** [NAVER-CAMPUS-HACKDAY/common#21]
## 주제 : 21. 전기자동차 이용 시 진행 가능한 최소시간 경로 탐색 기능 구현
우수참가자로 선정시 'NAVER'에서 '채용전환형 인턴십'의 참여기회가 주어집니다. (20년 2월 이내 졸업예정자 우대)

### 주제선정 배경
* 전기자동차는 한번 충전시 이동가능 거리가 기존 휘발유, 경유 차량에 비해 짧으므로 장거리 이동 시 충전소에 경유하는 경로가 필요
* 한번 충전 시 시간이 많이 필요하므로 최소한의 충전으로 이동 가능하도록 최적화 필요

### 개발 요구사항 (필수)
* 개발환경
  * Visual Studio
* JSON format 에 대한 기본 이해 필요
* Web API 사용에 대한 기본 지식 필요
* 경로 탐색 알고리즘에 대한 기본 지식 필요
  * BFS, DFS, Dijkstra, A* 등등

### 개발 요구사항 (선택)
* Viewer 구현
  * 결과를 보여주는 것이 main mission이 아니므로 자유 선택
  * Graphics library 이용 가능
  * 단순히 naver map url 을 반환하도록 하여 결과 확인 하도록 해도 됨

### Role
* Back-end Developer

### Technology 
* Windows
* Git
* gtest

### 개발언어
* C++

### 기타사항
* 경로 탐색 제약 사항
  * 전기 자동차는 충전 용량이 제한적
  * 충전 정도에 따라 이동 가능 거리 있음
  * 충전 시 소요시간 있음
  * 필요 시 완전히 충전 안하고 이동 가능

**Comment by ptc113** [comment]
- repository: https://github.com/NAVER-CAMPUS-HACKDAY/electric_vehicle_navigation
