### ISSUE TITLE
행사 질문드립니다.

### ISSUE THREAD

**Issue by JSpiner** [NAVER-CAMPUS-HACKDAY/common#40]
문의를 남길수 있는 연락처가 따로 없어 이슈로 남깁니다. 

1. 참가대상이 `대학(원)생`이라고 되어있는데, 휴학하고 회사에 재직중인 대학생도 참여가 가능한가요?
2. 회사 휴가 등 사유로, 행사일인 17(목) 일에 몇시부터 시작하는지, 늦게 참여할 수 있는지 궁금합니다.

감사합니다.

**Comment by Kang-heesuk** [comment]
안녕하세요. 행사와 관련된 문의는 hackday@navercorp.com으로 부탁드리겠습니다. 감사합니다
