### ISSUE TITLE
27. 웹소켓을 사용한 실시간 웹툰 퀴즈 대결

### ISSUE THREAD

**Issue by Kang-heesuk** [NAVER-CAMPUS-HACKDAY/common#8]
## 주제 : 웹소켓을 사용한 실시간 웹툰 퀴즈 대결
**!본 주제의 우수참가자로 선정시 '네이버웹툰'에서 학년에 따라 '체험형 인턴십(2,3학년)'과 '채용전환형 인턴십(4학년)'의 참여기회가 주어집니다.**

### 주제선정 배경
댓글에 보면 웹툰에 대한 지식을 자랑하는 사람들을 많이 볼 수 있는데, 이에 착안하여 정말로 누가 가장 웹툰에 대해서 잘 아는지 대결하는 웹툰 퀴즈 서비스 개발

### 개발 요구사항 (필수)
* Vue.js / React / Angular 중 하나의 프론트앤드 프레임워크를 사용하여 개발
* 웹툰에 대한 퀴즈를 등록할 수 있는 기능 개발
* 퀴즈는 정해진 시간에 시작
* 각 퀴즈에서 맞춘 사람들의 숫자가 표시되어야하고, 가장 많이 맞춘 사람의 아이디를 표시
* 웹소켓을 사용하여 실시간으로 퀴즈 대결을 할 수 있도록 개발

### 개발언어
* Java, javascript

### 플랫폼
* 웹

**Comment by lopun** [comment]
혹시 Java, Javascript 둘중에서 한가지만 선택 가능한가요?
